from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from broodmind.store.models import (
    AuditEvent,
    IntentRecord,
    MemoryEntry,
    PermitRecord,
    WorkerRecord,
    WorkerTemplateRecord,
)


class Store(Protocol):
    def create_worker(self, record: WorkerRecord) -> None: ...

    def update_worker_status(self, worker_id: str, status: str) -> None: ...

    def update_worker_result(
        self,
        worker_id: str,
        summary: str | None = None,
        output: dict[str, Any] | None = None,
        error: str | None = None,
    ) -> None: ...

    def get_worker(self, worker_id: str) -> WorkerRecord | None: ...

    def get_active_workers(self, older_than_minutes: int = 10) -> list[WorkerRecord]: ...

    def cleanup_old_workers(self, keep_recent_hours: int = 24, keep_completed_count: int = 100) -> int: ...

    def list_workers(self) -> list[WorkerRecord]: ...

    def upsert_worker_template(self, record: WorkerTemplateRecord) -> None: ...

    def list_worker_templates(self) -> list[WorkerTemplateRecord]: ...

    def get_worker_template(self, template_id: str) -> WorkerTemplateRecord | None: ...

    def delete_worker_template(self, template_id: str) -> None: ...

    def save_intent(self, record: IntentRecord) -> None: ...

    def update_intent_status(self, intent_id: str, status: str) -> None: ...

    def create_permit(self, record: PermitRecord) -> None: ...

    def consume_permit_atomic(self, permit_id: str, now: datetime) -> bool: ...

    def get_permit(self, permit_id: str, now: datetime) -> PermitRecord | None: ...

    def append_audit(self, event: AuditEvent) -> None: ...

    def list_audit(self, limit: int = 100) -> list[AuditEvent]: ...

    def get_audit(self, event_id: str) -> AuditEvent | None: ...

    def add_memory_entry(self, entry: MemoryEntry) -> None: ...

    def list_memory_entries(self, limit: int = 200) -> list[MemoryEntry]: ...

    def list_memory_entries_for_owner(self, owner_id: str, limit: int = 200) -> list[MemoryEntry]: ...

    def list_memory_entries_by_chat(self, chat_id: int, limit: int = 50) -> list[MemoryEntry]: ...

    def search_memory_entries_lexical(
        self,
        owner_id: str,
        query: str,
        limit: int = 80,
        exclude_chat_id: int | None = None,
    ) -> list[MemoryEntry]: ...

    def cleanup_old_memory(self, keep_days: int = 30, keep_count: int = 1000) -> int: ...

    def is_chat_bootstrapped(self, chat_id: int) -> bool: ...

    def mark_chat_bootstrapped(self, chat_id: int, ts: datetime) -> None: ...

    def get_chat_bootstrap_hash(self, chat_id: int) -> str | None: ...

    def set_chat_bootstrap_hash(self, chat_id: int, bootstrap_hash: str, ts: datetime) -> None: ...
