from __future__ import annotations

from datetime import datetime
from typing import Protocol

from broodmind.store.models import (
    AuditEvent,
    IntentRecord,
    MemoryEntry,
    PermitRecord,
    WorkerRecord,
    WorkerTemplateRecord,
)


class Store(Protocol):
    def create_worker(self, record: WorkerRecord) -> None: ...

    def update_worker_status(self, worker_id: str, status: str) -> None: ...

    def list_workers(self) -> list[WorkerRecord]: ...

    def upsert_worker_template(self, record: WorkerTemplateRecord) -> None: ...

    def list_worker_templates(self) -> list[WorkerTemplateRecord]: ...

    def get_worker_template(self, template_id: str) -> WorkerTemplateRecord | None: ...

    def save_intent(self, record: IntentRecord) -> None: ...

    def update_intent_status(self, intent_id: str, status: str) -> None: ...

    def create_permit(self, record: PermitRecord) -> None: ...

    def consume_permit_atomic(self, permit_id: str, now: datetime) -> bool: ...

    def get_permit(self, permit_id: str, now: datetime) -> PermitRecord | None: ...

    def append_audit(self, event: AuditEvent) -> None: ...

    def list_audit(self, limit: int = 100) -> list[AuditEvent]: ...

    def get_audit(self, event_id: str) -> AuditEvent | None: ...

    def add_memory_entry(self, entry: MemoryEntry) -> None: ...

    def list_memory_entries(self, limit: int = 200) -> list[MemoryEntry]: ...

    def list_memory_entries_by_chat(self, chat_id: int, limit: int = 50) -> list[MemoryEntry]: ...

    def is_chat_bootstrapped(self, chat_id: int) -> bool: ...

    def mark_chat_bootstrapped(self, chat_id: int, ts: datetime) -> None: ...
