from __future__ import annotations

from typing import Any, Protocol


class BrowserBackend(Protocol):
    async def open(self, args: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]: ...

    async def tabs(self, args: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]: ...

    async def focus_tab(self, args: dict[str, Any], ctx: dict[str, Any]) -> str: ...

    async def navigate(self, args: dict[str, Any], ctx: dict[str, Any]) -> str: ...

    async def snapshot(self, args: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]: ...

    async def click(self, args: dict[str, Any], ctx: dict[str, Any]) -> str: ...

    async def type(self, args: dict[str, Any], ctx: dict[str, Any]) -> str: ...

    async def close(self, args: dict[str, Any], ctx: dict[str, Any]) -> str: ...

    async def wait_for(self, args: dict[str, Any], ctx: dict[str, Any]) -> str: ...

    async def extract(self, args: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]: ...

    async def screenshot(self, args: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]: ...
