from __future__ import annotations

import asyncio
import json
import logging
import os
import base64
import uuid
from pathlib import Path
from typing import Any

import structlog

from broodmind.providers.base import InferenceProvider, Message
from broodmind.memory.service import MemoryService
from broodmind.memory.canon import CanonService
from broodmind.queen.prompt_builder import build_queen_prompt, build_bootstrap_context_prompt
from broodmind.tools.registry import ToolPolicy, ToolPolicyPipelineStep, ToolSpec, filter_tools
from broodmind.tools.tools import get_tools
from broodmind.utils import is_heartbeat_ok, is_control_response
from broodmind.workers.contracts import WorkerResult

logger = structlog.get_logger(__name__)
_MAX_PLAN_STEPS = 10
_MAX_VERIFY_CONTEXT_CHARS = 20000


async def route_or_reply(
    queen: Any,
    provider: InferenceProvider,
    memory: MemoryService,
    user_text: str,
    chat_id: int,
    bootstrap_context: str,
    *,
    internal_followup: bool = False,
    show_typing: bool = True,
    images: list[str] | None = None,
    include_wakeup: bool = True,
) -> str:
    """Core routing logic: decide whether to use tools or reply to user."""
    # Internal chat_id (<= 0) should not trigger typing indicators.
    if chat_id > 0 and show_typing:
        await queen.set_typing(chat_id, True)
    
    await queen.set_thinking(True)
    try:
        is_ws = getattr(queen, "is_ws_active", False)
        wake_notice = ""
        if include_wakeup and hasattr(queen, "peek_context_wakeup"):
            wake_notice = str(queen.peek_context_wakeup(chat_id) or "")
        messages = await build_queen_prompt(
            store=queen.store, 
            memory=memory, 
            canon=queen.canon, 
            user_text=user_text, 
            chat_id=chat_id, 
            bootstrap_context=bootstrap_context,
            is_ws=is_ws,
            images=images,
            wake_notice=wake_notice,
        )
        _log_system_prompt(messages, "route")
        
        queen_tools, ctx = _get_queen_tools(queen, chat_id)
        logger.info("Queen tools fetched: count=%d", len(queen_tools))
        plan = await _build_plan(provider, messages, bool(queen_tools))
        if plan:
            await _persist_plan(memory, chat_id, plan)
            logger.info(
                "Queen plan ready",
                mode=plan["mode"],
                steps=len(plan.get("steps", [])),
            )
            if plan["mode"] == "reply":
                return await _finalize_response(
                    provider=provider,
                    messages=messages,
                    response_text=str(plan.get("response", "")),
                    internal_followup=internal_followup,
                )
            plan_steps = plan.get("steps", [])
            if plan_steps:
                plan_block = "\n".join([f"{idx + 1}. {step}" for idx, step in enumerate(plan_steps)])
                messages.append(
                    Message(
                        role="system",
                        content=(
                            "Execution plan generated by planner. Execute steps in order and recover gracefully from failures.\n"
                            "<execution_plan>\n"
                            f"{plan_block}\n"
                            "</execution_plan>"
                        ),
                    )
                )
        tool_capable = getattr(provider, "complete_with_tools", None)
        
        if callable(tool_capable):
            tools = [spec.to_openai_tool() for spec in queen_tools]
            last_error: str | None = None
            had_tool_calls = False
            max_attempts = 10
            
            for _ in range(max_attempts):
                try:
                    result = await provider.complete_with_tools(messages, tools=tools, tool_choice="auto")
                except Exception as e:
                    # If we have images, this might be a multi-modal conflict (e.g. z.ai GLM-4 doesn't support tools + vision).
                    # Fallback strategy: Save images to disk and retry with a text-only prompt pointing to the files.
                    if images:
                        logger.warning("Vision+Tools failed; attempting save-to-disk fallback", error=str(e))
                        try:
                            # 1. Save images to disk
                            saved_paths = []
                            workspace_dir = Path(os.getenv("BROODMIND_WORKSPACE_DIR", "workspace")).resolve()
                            img_dir = workspace_dir / "tmp" / "telegram_images"
                            img_dir.mkdir(parents=True, exist_ok=True)
                            
                            for idx, img_data in enumerate(images):
                                # expect data:image/jpeg;base64,....
                                if "," in img_data:
                                    header, b64_str = img_data.split(",", 1)
                                    ext = ".jpg"
                                    if "png" in header: ext = ".png"
                                    elif "webp" in header: ext = ".webp"
                                else:
                                    b64_str = img_data
                                    ext = ".jpg" # assume jpg
                                
                                file_name = f"img_{uuid.uuid4()}{ext}"
                                file_path = img_dir / file_name
                                with open(file_path, "wb") as f:
                                    f.write(base64.b64decode(b64_str))
                                saved_paths.append(str(file_path))
                            
                            # 2. Construct new text-only message
                            fallback_text = (
                                f"{user_text}\n\n"
                                "[SYSTEM NOTE: User sent {len(images)} image(s). Direct vision processing failed (provider rejected multimodal payload). "
                                "The images have been saved locally at:\n" + 
                                "\n".join([f"- {p}" for p in saved_paths]) + 
                                "\nIf you have file analysis tools, you can use them on these paths. Otherwise, ask the user for a description.]"
                            )
                            
                            # 3. Replace the last message (which had the image payload) with text-only version
                            # effectively 'popping' the failed multimodal message and replacing it
                            logger.info("Retrying with text-only fallback and saved images", count=len(saved_paths))
                            messages[-1] = {"role": "user", "content": fallback_text}
                            
                            # 4. Disable images flag so we don't loop forever if this retry fails too
                            images = None 
                            continue 
                            
                        except Exception as fallback_exc:
                            logger.error("Fallback save-and-retry failed", error=str(fallback_exc))
                            return "I see you sent an image, but I am unable to process it. My current model configuration might not support vision, and I could not save it for tool analysis."
                    raise e
                
                content_raw = result.get("content", "")
                tool_calls = result.get("tool_calls") or []
                
                if tool_calls:
                    had_tool_calls = True
                    assistant_msg: dict[str, Any] = {"role": "assistant", "tool_calls": tool_calls}
                    if content_raw:
                        assistant_msg["content"] = content_raw
                    messages.append(assistant_msg)
                    
                    for call in tool_calls:
                        tool_result = await _handle_queen_tool_call(call, queen_tools, ctx)
                        tool_result_text = (
                            tool_result
                            if isinstance(tool_result, str)
                            else json.dumps(tool_result, ensure_ascii=False)
                        )
                        messages.append(
                            {"role": "tool", "tool_call_id": call.get("id"), "content": tool_result_text}
                        )
                        if "error" in tool_result_text.lower() or "failed" in tool_result_text.lower():
                            last_error = tool_result_text
                    continue
                
                if content_raw:
                    logger.debug("Queen output", output=content_raw)
                return await _finalize_response(
                    provider=provider,
                    messages=messages,
                    response_text=content_raw,
                    internal_followup=internal_followup,
                )
                
            if had_tool_calls:
                if internal_followup:
                    return "NO_USER_RESPONSE"
                # Force a final response without tools to explain progress.
                messages.append(
                    Message(
                        role="system",
                        content="You have reached the tool call limit for this turn. Summarize what you have initiated and let the user know you are processing their request.",
                    )
                )
                final_resp = await _complete_text(provider, messages, context="tool_limit_fallback")
                return await _finalize_response(
                    provider=provider,
                    messages=messages,
                    response_text=final_resp,
                    internal_followup=internal_followup,
                )
                
            if last_error and _looks_like_tool_error(last_error):
                if internal_followup:
                    return "NO_USER_RESPONSE"
                messages.append(
                    Message(
                        role="system",
                        content=f"A tool call failed: {last_error}. Explain the problem to the user naturally and ask for guidance if needed.",
                    )
                )
                final_resp = await _complete_text(provider, messages, context="tool_error_fallback")
                return await _finalize_response(
                    provider=provider,
                    messages=messages,
                    response_text=final_resp,
                    internal_followup=internal_followup,
                )
                
            return ""
            
        response_raw = await _complete_text(provider, messages, context="plain_completion")
        logger.debug("Queen output", output=response_raw)
        return await _finalize_response(
            provider=provider,
            messages=messages,
            response_text=response_raw,
            internal_followup=internal_followup,
        )
    except Exception:
        logger.exception("Error in route_or_reply")
        raise
    finally:
        await queen.set_thinking(False)
        if chat_id > 0 and show_typing:
            logger.debug("Toggling typing indicator off", chat_id=chat_id)
            await queen.set_typing(chat_id, False)


async def route_worker_result_back_to_queen(
    queen: Any,
    chat_id: int,
    task_text: str,
    result: WorkerResult,
) -> str:
    """Decide next steps after a worker completes its task."""
    output_summary = result.output
    output_truncated = False
    available_keys = []

    if isinstance(result.output, dict):
        available_keys = list(result.output.keys())
        if len(json.dumps(result.output)) > 8000:
            output_summary = {k: f"<{type(v).__name__}>" for k, v in result.output.items()}
            output_truncated = True

    payload = {
        "task": task_text,
        "summary": result.summary,
        "output": output_summary,
        "output_truncated": output_truncated,
        "available_keys": available_keys,
        "questions": result.questions,
        "knowledge_proposals": [p.model_dump() for p in result.knowledge_proposals],
        "tools_used": result.tools_used,
    }
    payload_json = json.dumps(payload, ensure_ascii=False)

    worker_result_prompt = (
        "Worker completed. Decide and execute next action based on this payload.\n"
        "<worker_result>\n"
        f"{payload_json}\n"
        "</worker_result>\n\n"
        "If the output is truncated and you need specific details, use `get_worker_output_path`.\n"
        "If there are knowledge_proposals, review them and use `manage_canon` to save them if valid.\n"
        "If a user-facing response is required now, provide it in plain text.\n"
        "If no user-facing response is needed, return exactly: NO_USER_RESPONSE"
    )
    
    bootstrap_context = await build_bootstrap_context_prompt(queen.store, chat_id)
    reply_text = await route_or_reply(
        queen,
        queen.provider,
        queen.memory,
        worker_result_prompt,
        chat_id,
        bootstrap_context.content,
        internal_followup=True,
    )
    return normalize_plain_text(reply_text)


def should_send_worker_followup(text: str) -> bool:
    """Determine if a worker follow-up should be sent to the user."""
    if is_control_response(text):
        return False
    return True


def normalize_plain_text(text: str) -> str:
    cleaned = text.replace("\r\n", "\n").replace("\r", "\n")
    return cleaned.strip()


def _looks_like_tool_error(text: str) -> bool:
    lowered = text.lower()
    return " error" in lowered or "failed" in lowered


def _log_system_prompt(messages: list[Message], label: str) -> None:
    system_lengths = [len(m.content) for m in messages if m.role == "system" and m.content]
    if system_lengths:
        logger.debug(
            "Queen system prompt",
            label=label,
            parts=len(system_lengths),
            total_chars=sum(system_lengths),
        )


def _get_queen_tools(queen: Any, chat_id: int) -> tuple[list[ToolSpec], dict[str, object]]:
    perms = {
        "filesystem_read": True,
        "filesystem_write": True,
        "worker_manage": True,
        "llm_subtask": True,
        "canon_manage": True,
        "network": True,
        "exec": True,
        "service_read": True,
        "service_control": True,
        "deploy_control": True,
        "db_admin": True,
        "security_audit": True,
        "self_control": True,
        "mcp_exec": True,
        "skill_use": True,
        "skill_manage": True,
    }
    ctx = {
        "base_dir": Path(os.getenv("BROODMIND_WORKSPACE_DIR", "workspace")).resolve(),
        "queen": queen,
        "chat_id": chat_id
    }
    mcp_manager = getattr(queen, "mcp_manager", None)
    policy_steps = [
        ToolPolicyPipelineStep(
            label="queen.raw_fetch_denylist",
            policy=ToolPolicy(deny=["web_fetch", "markdown_new_fetch", "fetch_plan_tool"]),
        )
    ]
    tool_specs = filter_tools(
        get_tools(mcp_manager=mcp_manager),
        permissions=perms,
        policy_pipeline_steps=policy_steps,
    )
    return tool_specs, ctx


async def _handle_queen_tool_call(call: dict, tools: list[ToolSpec], ctx: dict[str, object]) -> str:
    function = call.get("function") or {}
    name = function.get("name")
    args_raw = function.get("arguments", "{}")
    try:
        args = json.loads(args_raw) if isinstance(args_raw, str) else args_raw
    except Exception:
        args = {}
    
    logger.debug("Queen tool call", tool_name=name, args=args)
    for spec in tools:
        if spec.name == name:
            if spec.is_async:
                import inspect
                result = spec.handler(args, ctx)
                if inspect.isawaitable(result):
                    result = await result
            else:
                result = await asyncio.to_thread(spec.handler, args, ctx)
            logger.debug("Queen tool result", tool_name=name, result_preview=f"{str(result)[:200]}...")
            return result
    return f"Unknown tool: {name}"


async def _build_plan(
    provider: InferenceProvider,
    messages: list[Message | dict[str, Any]],
    has_tools: bool,
) -> dict[str, Any] | None:
    planning_prompt = (
        "Create a brief execution plan for this turn. Return JSON only with keys: "
        '{"mode":"execute|reply","steps":["..."],"response":"..."}.\n'
        "- Use mode=reply when no tools/workers are needed and a direct answer is sufficient.\n"
        "- Use mode=execute when tools/workers are needed; provide 1-8 concrete steps.\n"
        "- If mode=reply, include response.\n"
        "- If mode=execute, response is optional."
    )
    planner_messages = list(messages) + [Message(role="system", content=planning_prompt)]
    try:
        raw = await _complete_text(provider, planner_messages, context="planner")
    except Exception:
        logger.debug("Planner step skipped due to provider error", exc_info=True)
        return None

    payload = _extract_json_object(raw)
    if not isinstance(payload, dict):
        return None
    return _normalize_plan_payload(payload, has_tools)


async def _persist_plan(memory: MemoryService, chat_id: int, plan: dict[str, Any]) -> None:
    mode = str(plan.get("mode", "execute"))
    steps = [str(step) for step in plan.get("steps", []) if str(step).strip()]
    response = str(plan.get("response", "")).strip()
    plan_summary = (
        f"Planner mode={mode}; steps={len(steps)}"
        + (f"; response_len={len(response)}" if response else "")
    )
    try:
        await memory.add_message(
            "system",
            plan_summary,
            {
                "chat_id": chat_id,
                "planner": True,
                "mode": mode,
                "steps": steps,
            },
        )
    except Exception:
        logger.debug("Failed to persist planner trace", exc_info=True)


def _extract_json_object(raw: str) -> dict[str, Any] | None:
    if not raw:
        return None
    candidates = [raw.strip()]
    stripped = raw.strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        if len(lines) >= 3 and lines[-1].strip() == "```":
            candidates.append("\n".join(lines[1:-1]).strip())
    for candidate in candidates:
        try:
            parsed = json.loads(candidate)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            continue
    return None


def _normalize_plan_payload(payload: dict[str, Any], has_tools: bool) -> dict[str, Any] | None:
    mode = str(payload.get("mode", "execute")).strip().lower()
    steps_raw = payload.get("steps")
    steps: list[str] = []
    if isinstance(steps_raw, list):
        steps = [str(step).strip() for step in steps_raw if str(step).strip()]
    response = str(payload.get("response", "")).strip()

    if mode not in {"reply", "execute"}:
        mode = "execute"

    if mode == "reply":
        if not response:
            return None
        return {"mode": "reply", "response": response, "steps": []}

    # If no tools are available and planner requested execute, degrade to reply when possible.
    if not has_tools and response:
        return {"mode": "reply", "response": response, "steps": []}

    if not steps:
        return None
    return {"mode": "execute", "steps": steps[:_MAX_PLAN_STEPS], "response": response}


async def _finalize_response(
    provider: InferenceProvider,
    messages: list[Message | dict[str, Any]],
    response_text: str,
    *,
    internal_followup: bool,
) -> str:
    cleaned = normalize_plain_text(response_text or "")
    if not cleaned:
        return cleaned
    return cleaned


async def _verify_final_response(
    provider: InferenceProvider,
    messages: list[Message | dict[str, Any]],
    candidate: str,
) -> str:
    context = _messages_to_text(messages)
    prompt = (
        "You are a strict response verifier. Compare the assistant draft response against the evidence context.\n"
        "Return JSON only with keys:\n"
        '{"verdict":"approved|revised|insufficient_evidence","response":"...","missing_evidence":["..."],"confidence":0.0}\n'
        "Rules:\n"
        "- approved: draft is well-supported.\n"
        "- revised: rewrite conservatively to match evidence.\n"
        "- insufficient_evidence: if claims are not backed; provide a short user-facing follow-up request.\n"
        "- Do not invent new facts."
        "\n\n<EVIDENCE>\n"
        f"{context}\n"
        "</EVIDENCE>\n\n"
        "<DRAFT_RESPONSE>\n"
        f"{candidate}\n"
        "</DRAFT_RESPONSE>"
    )
    try:
        raw = await _complete_text(
            provider,
            [Message(role="system", content=prompt)],
            context="verifier",
        )
    except Exception:
        logger.debug("Verifier step skipped due to provider error", exc_info=True)
        return candidate

    payload = _extract_json_object(raw)
    normalized = _normalize_verification_payload(payload)
    if not normalized:
        return candidate

    verdict = normalized["verdict"]
    confidence = normalized["confidence"]
    if verdict == "approved" and confidence >= 0.45:
        return candidate
    if verdict == "revised" and normalized["response"]:
        return normalized["response"]
    if verdict == "insufficient_evidence":
        return _build_insufficient_evidence_response(normalized, candidate)
    return candidate


def _messages_to_text(messages: list[Message | dict[str, Any]], max_chars: int = _MAX_VERIFY_CONTEXT_CHARS) -> str:
    lines: list[str] = []
    for msg in messages[-14:]:
        if isinstance(msg, Message):
            role = msg.role
            content = msg.content
        else:
            role = str(msg.get("role", "unknown"))
            content = msg.get("content", "")
        if isinstance(content, list):
            safe_content = json.dumps(content, ensure_ascii=False)
        else:
            safe_content = str(content)
        if safe_content:
            lines.append(f"{role}: {safe_content}")
    merged = "\n".join(lines)
    if len(merged) > max_chars:
        return merged[-max_chars:]
    return merged


def _normalize_verification_payload(payload: dict[str, Any] | None) -> dict[str, Any] | None:
    if not isinstance(payload, dict):
        return None
    verdict = str(payload.get("verdict", "")).strip().lower()
    if verdict not in {"approved", "revised", "insufficient_evidence"}:
        return None
    response = str(payload.get("response", "")).strip()
    missing = payload.get("missing_evidence") or []
    if not isinstance(missing, list):
        missing = []
    missing = [str(item).strip() for item in missing if str(item).strip()]
    confidence_raw = payload.get("confidence", 0.0)
    try:
        confidence = float(confidence_raw)
    except Exception:
        confidence = 0.0
    confidence = max(0.0, min(1.0, confidence))
    return {
        "verdict": verdict,
        "response": response,
        "missing_evidence": missing,
        "confidence": confidence,
    }


def _build_insufficient_evidence_response(payload: dict[str, Any], candidate: str) -> str:
    response = payload.get("response", "").strip()
    if response:
        lower = response.lower()
        technical_markers = (
            "provided evidence",
            "cannot confidently verify",
            "draft includes details",
            "not supported by",
        )
        if not any(marker in lower for marker in technical_markers):
            return response
    missing = payload.get("missing_evidence") or []
    if missing:
        return (
            "I may be missing enough evidence to confirm this fully. "
            f"Could you share or confirm: {missing[0]}?"
        )
    return (
        "I may be missing enough evidence to give a confident answer yet. "
        "If you want, I can run an additional targeted check."
    )


async def _complete_text(
    provider: InferenceProvider,
    messages: list[Message | dict[str, Any]],
    *,
    context: str,
) -> str:
    sanitized = _sanitize_messages_for_complete(messages)
    try:
        return await provider.complete(sanitized)
    except Exception:
        logger.debug(
            "Text completion failed after sanitization",
            context=context,
            message_shape=_message_shape(sanitized),
            exc_info=True,
        )
        raise


def _sanitize_messages_for_complete(messages: list[Message | dict[str, Any]]) -> list[dict[str, str]]:
    sanitized: list[dict[str, str]] = []
    for msg in messages:
        role: str
        content: Any
        if isinstance(msg, Message):
            role = msg.role
            content = msg.content
        else:
            role = str(msg.get("role", "assistant"))
            content = msg.get("content", "")

        normalized_role = role if role in {"system", "user", "assistant"} else "assistant"
        if role == "tool":
            continue

        normalized_content = _coerce_content_to_text(content)
        if not normalized_content:
            continue

        sanitized.append({"role": normalized_role, "content": normalized_content})

    if not sanitized:
        sanitized.append({"role": "user", "content": "Continue."})
    elif not any(msg.get("role") == "user" for msg in sanitized):
        sanitized.append(
            {
                "role": "user",
                "content": "Please follow the instructions above and provide the best supported response.",
            }
        )
    return sanitized


def _coerce_content_to_text(content: Any) -> str:
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        text_parts: list[str] = []
        for item in content:
            if not isinstance(item, dict):
                continue
            item_type = str(item.get("type", "")).lower()
            if item_type == "text":
                text_val = str(item.get("text", "")).strip()
                if text_val:
                    text_parts.append(text_val)
            elif item_type == "image_url":
                text_parts.append("[image omitted for text-only completion]")
        return "\n".join(text_parts).strip()
    try:
        return json.dumps(content, ensure_ascii=False)
    except Exception:
        return str(content or "")


def _message_shape(messages: list[dict[str, str]]) -> list[dict[str, Any]]:
    shape: list[dict[str, Any]] = []
    for msg in messages[:24]:
        content = msg.get("content", "")
        shape.append(
            {
                "role": msg.get("role"),
                "content_type": type(content).__name__,
                "content_len": len(content) if isinstance(content, str) else None,
            }
        )
    return shape
